version: '3.8'
services:
  backend:
    build: ./backend/
    image: myapp_backend
    container_name: miniapp-backend
    ports:
      - "5000:5000"
  
  client:
    build: ./client/
    image: myapp_client
    container_name: miniapp-client
    ports:
      - "3000:3000"  